version: "3.4"

services:
  # db:
  #   image: mysql:8.0
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root_password
  #   ports:
  #     - "3306:3306"
  #   networks:
  #     - project_network
  backend:
    image: ssimunec/hackaton2023-backend
    ports:
      - "8084:8080"
    restart: always
    container_name: hack-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - project_network
    environment:
      - PORT=8080
networks:
  project_network:
    driver: bridge
